version: "3"
services:
  jekyll:
    command: jekyll serve -s jekyll --incremental --livereload
    image: jekyll/jekyll:3.8.6
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:35729:35729
