version: "3"
services:
  jekyll:
    command: bash scripts/docker_command.sh
    working_dir: /root
    image: ruby:2.7.2
    volumes:
      - ".:/root"
    ports:
      - 127.0.0.1:4000:4000
      - 127.0.0.1:35729:35729
  https:
    image: "caddy:2"
    ports:
      - '127.0.0.1:443:443'
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
